//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoPhongVu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachSanPham
    {
        public long id { get; set; }
        public long idSanPham { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> giamGia { get; set; }
        public long idHoaDon { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
